#pragma once

#ifdef __EMSCRIPTEN__
#define BYTESIZED_GLSL_VERSION "#version 300 es\n"
#endif

#ifndef BYTESIZED_GLSL_VERSION
#define BYTESIZED_GLSL_VERSION "#version 330 core\n"
#endif

#ifndef BYTESIZED_VERTEXARRAY_COUNT
#define BYTESIZED_VERTEXARRAY_COUNT 50
#endif
#ifndef BYTESIZED_VERTEXBUFFER_COUNT
#define BYTESIZED_VERTEXBUFFER_COUNT 100
#endif
#ifndef BYTESIZED_TEXTURE_COUNT
#define BYTESIZED_TEXTURE_COUNT 20
#endif
#ifndef BYTESIZED_MATERIAL_COUNT
#define BYTESIZED_MATERIAL_COUNT 20
#endif
#ifndef BYTESIZED_UNIFORMBUFFER_COUNT
#define BYTESIZED_UNIFORMBUFFER_COUNT 10
#endif
#ifndef BYTESIZED_MESH_COUNT
#define BYTESIZED_MESH_COUNT 50
#endif
#ifndef BYTESIZED_PRIMITIVE_COUNT
#define BYTESIZED_PRIMITIVE_COUNT 50
#endif
#ifndef BYTESIZED_NODE_COUNT
#define BYTESIZED_NODE_COUNT 100
#endif
#ifndef BYTESIZED_SCENE_COUNT
#define BYTESIZED_SCENE_COUNT 10
#endif
#ifndef BYTESIZED_SKIN_COUNT
#define BYTESIZED_SKIN_COUNT 10
#endif
#ifndef BYTESIZED_SHADER_COUNT
#define BYTESIZED_SHADER_COUNT 30
#endif
#ifndef BYTESIZED_SHADERPROGRAM_COUNT
#define BYTESIZED_SHADERPROGRAM_COUNT 20
#endif
#ifndef BYTESIZED_TEXT_COUNT
#define BYTESIZED_TEXT_COUNT 10
#endif
#ifndef BYTESIZED_FRAMEBUFFER_COUNT
#define BYTESIZED_FRAMEBUFFER_COUNT 10
#endif
#ifndef BYTESIZED_ANIMATION_COUNT
#define BYTESIZED_ANIMATION_COUNT 20
#endif
#ifndef BYTESIZED_PLAYBACK_COUNT
#define BYTESIZED_PLAYBACK_COUNT 10
#endif

#if BYTESIZED_SKIN_COUNT > 0 & BYTESIZED_ANIMATION_COUNT > 0 & BYTESIZED_PLAYBACK_COUNT > 0
#define BYTESIZED_USE_SKINNING 1
#endif